// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAg9Mz0gk8pFiqrU0N7lVDLz5MlECzoBo',
    appId: '1:537322672223:web:31a03dcc76150a44bccbea',
    messagingSenderId: '537322672223',
    projectId: 'restaurante-bb8ec',
    authDomain: 'restaurante-bb8ec.firebaseapp.com',
    storageBucket: 'restaurante-bb8ec.firebasestorage.app',
    measurementId: 'G-DR2JR3HRXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcegLelPc_6i9UctmXUfL5HJqrnFptmr0',
    appId: '1:537322672223:android:5fe4c92efa6fa2aabccbea',
    messagingSenderId: '537322672223',
    projectId: 'restaurante-bb8ec',
    storageBucket: 'restaurante-bb8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRy6caejqSCUNlk5yRFvFbA9CCxA7Ri8',
    appId: '1:537322672223:ios:869322b36798c9a2bccbea',
    messagingSenderId: '537322672223',
    projectId: 'restaurante-bb8ec',
    storageBucket: 'restaurante-bb8ec.firebasestorage.app',
    iosBundleId: 'com.example.respaso',
  );

}